version: 2
jobs:
  e2e:
    docker:
      - image: aviramstern/aviram-orbs:ubuntu-go-node
    steps:
      - checkout
      - run: ./test-e2e.sh
      - store_artifacts:
          path: _out
      - store_test_results:
          path: _reports
  gas:
    docker:
      - image: aviramstern/aviram-orbs:ubuntu-go-node
    steps:
      - checkout
      - run: ./test-gas.sh
      - store_artifacts:
          path: _out
      - store_test_results:
          path: _reports
  coverage:
    docker:
      - image: aviramstern/aviram-orbs:ubuntu-go-node
    steps:
      - checkout
      - run: ./test-coverage.sh
      - store_artifacts:
          path: _out
      - store_test_results:
          path: _reports

workflows:
  version: 2
  build:
    jobs:
      - e2e
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - e2e
      - coverage
      - gas
