version: 2
jobs:
  posv2-contracts-e2e:
    docker:
      - image: aviramstern/aviram-orbs:ubuntu-go-node
    steps:
      - checkout
      - run: ./test.sh
      - store_artifacts:
          path: _out
      - store_test_results:
          path: _reports

workflows:
  version: 2
  build:
    jobs:
      - posv2-contracts-e2e
